"""Write docs/sw.js: a service worker that precaches the website and app for offline use.

The cache name carries a hash of every precached file, so any change to the site
produces a new cache and phones pick up the update on their next visit.
Run after changing anything in docs/:  python analysis/build_sw.py
"""
import hashlib, json, pathlib

DOCS = pathlib.Path(__file__).resolve().parents[1] / "docs"
EXCLUDE_SUFFIX = {".md", ".txt", ".yml", ".pdf", ".mp4", ".webm"}   # large downloads are fetched on demand, not precached
EXCLUDE_PREFIX = ("data/terrain/", "assets/vendor/three/")        # the 3D terrain page (about 4 MB) needs a connection anyway


def files():
    out = []
    for p in sorted(DOCS.rglob("*")):
        if not p.is_file() or p.name == "sw.js" or p.suffix in EXCLUDE_SUFFIX:
            continue
        rel = p.relative_to(DOCS).as_posix()
        if rel.startswith(".") or "/." in rel or rel.startswith(EXCLUDE_PREFIX):
            continue
        out.append(rel)
    # large photos: keep the phone-sized version of each image (the smallest one if none is phone-sized)
    small = ("-600.webp", "-800.webp", "-900.webp", "-562.webp")
    imgs = [r for r in out if r.startswith("img/") and r.endswith(".webp")]
    keep = set()
    for stem in {r.rsplit("-", 1)[0] for r in imgs}:
        vs = sorted((r for r in imgs if r.rsplit("-", 1)[0] == stem), key=lambda r: int(r.rsplit("-", 1)[1][:-5]))
        phone = [r for r in vs if r.endswith(small)]
        keep.update(phone or vs[:1])
    return [r for r in out if not (r.startswith("img/") and r.endswith(".webp")) or r in keep]


def main():
    fl = files()
    h = hashlib.sha256()
    for rel in fl:
        h.update(rel.encode()); h.update((DOCS / rel).read_bytes())
    ver = h.hexdigest()[:10]
    size = sum((DOCS / r).stat().st_size for r in fl)
    js = f"""/* Generated by analysis/build_sw.py. Do not edit by hand. */
const VERSION = "mlfg-{ver}";
const PRECACHE = {json.dumps(["./", "app/"] + fl, indent=0)};
const RUNTIME = "mlfg-runtime";
const TILE_MAX = 400;

self.addEventListener("install", e => {{
  // cache: "reload" skips the browser's HTTP cache, so a new version never precaches stale copies
  e.waitUntil(caches.open(VERSION).then(c => c.addAll(PRECACHE.map(u => new Request(u, {{cache: "reload"}})))).then(() => self.skipWaiting()));
}});
self.addEventListener("activate", e => {{
  e.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(k => k !== VERSION && k !== RUNTIME).map(k => caches.delete(k))))
    .then(() => self.clients.claim()));
}});

async function trim(cache, max) {{
  const keys = await cache.keys();
  for (let i = 0; i < keys.length - max; i++) await cache.delete(keys[i]);
}}

self.addEventListener("fetch", e => {{
  const req = e.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin === location.origin) {{
    // site files: cache first (the version hash handles updates), network fallback
    // a folder URL ("app/") is served from its index.html; offline, pages fall back to the home page
    e.respondWith(caches.match(req, {{ignoreSearch: true}})
      .then(hit => hit || (url.pathname.endsWith("/") ? caches.match(url.pathname + "index.html", {{ignoreSearch: true}}) : null))
      .then(hit => hit || fetch(req).catch(() => req.mode === "navigate" ? caches.match("index.html") : Response.error())));
    return;
  }}
  if (url.hostname === "api.weather.gov") return;  // the app caches the forecast itself
  if (/fonts\\.(googleapis|gstatic)\\.com$/.test(url.hostname) || /nationalmap\\.gov$/.test(url.hostname)) {{
    // fonts and USGS map tiles (public domain; OSM tiles are left to the browser cache per its tile policy): serve from cache, refresh in the background
    e.respondWith(caches.open(RUNTIME).then(async c => {{
      const hit = await c.match(req);
      const net = fetch(req).then(r => {{ if (r.ok || r.type === "opaque") {{ c.put(req, r.clone()); trim(c, TILE_MAX); }} return r; }}).catch(() => hit);
      return hit || net;
    }}));
  }}
}});
"""
    (DOCS / "sw.js").write_text(js)
    print(f"sw.js: {len(fl)} files, {size/1e6:.1f} MB, version {ver}")


if __name__ == "__main__":
    main()
